### ISSUE TITLE
Enable users to submit issues with the website/api

### ISSUE THREAD

**Issue by ikke09** [ikke09/Tabak-Taste#3]
## Idea
Small form for the user on the frontend to easily submit issues:
Category: Data Duplicate | Data Error | Design | Feedback | Other
Subject: String
Description: String

## Possible Solutions
* GitHub API could be used in order to create issues in this repo -> Repo used as ticket system
* submits are stored in own database table

## TODOs
* [ ] Add Form on frontend
* [ ] Extend API to retrieve Data
* [ ] Save data on database or as issue in this repo
