### ISSUE TITLE
Tobacco Detail View

### ISSUE THREAD

**Issue by ikke09** [ikke09/Tabak-Taste#6]
## Idea
Enable that the user can click on a tobacco so that a detail view will be shown.
The detail View shows more informations like the source or ean when available.

Also additonal action button are possible on that view. For example share, mark as favorite or mark as duplicate

## TODOs
* [ ] Create Detail-View
* [ ] Make tobacco card clickable that routes to detail view
* [x] Expand api to load a single tobacco
